name: AutoUPnP
version: '${version}'
main: org.ronse.autoupnp.AutoUPnP
api-version: 1.19
load: STARTUP
authors: [ 4ronse ]
description: Automatically forwards UPnP ports

commands:
  open-port:
    aliases:
      - add-port
    description: Opens a UPnP Port
    usage: /open-port <IP> <Internal Port> <External Port> <Protocol> <Description>
  list-ports:
    description: Lists all open ports
    usage: /list-ports
  close-port:
    description:  Closes specified port
    usage: /close-port <Protocol> <External Port>
  reload-ports:
    description: Closes all ports and reload ports.yml
    usage: /reload-ports
  test-command:
    description: simple test command


permissions:
  AutoUPnP.manage:
    default: true
    description: Allows player to manage ports

default-permission: op